-- Core tables
create table if not exists attendance (
  id bigint generated by default as identity primary key,
  student_id text not null,
  nisn text,
  nama text,
  kelas text,
  type text check (type in ('masuk','pulang')) default 'masuk',
  method text check (method in ('face','manual')) default 'face',
  timestamp_iso text,
  date_id text,
  time_id text,
  status text default 'hadir',
  inserted_at timestamp with time zone default now()
);

create table if not exists face_descriptors (
  student_id text primary key,
  nisn text,
  nama text,
  descriptors jsonb not null,
  registered_at timestamp with time zone default now()
);

create table if not exists profiles (
  user_id text primary key,
  role text check (role in ('admin','guru','siswa')),
  nama text,
  email text,
  nip text,
  kelas text,
  phone text,
  address text,
  avatar_url text,
  updated_at timestamp with time zone default now()
);

create table if not exists grades (
  id bigint generated by default as identity primary key,
  student_id text not null,
  nisn text,
  nama_siswa text,
  kelas text,
  mata_pelajaran text,
  kategori text check (kategori in ('UH','UTS','UAS','Tugas','Praktik')),
  nilai numeric,
  keterangan text,
  teacher_id text,
  teacher_name text,
  tanggal timestamp with time zone default now()
);

create table if not exists exams (
  id bigint generated by default as identity primary key,
  exam_id text unique,
  title text,
  mata_pelajaran text,
  kelas text,
  deskripsi text,
  waktu_mulai timestamptz,
  waktu_selesai timestamptz,
  durasi integer,
  questions jsonb,
  teacher_id text,
  teacher_name text,
  status text default 'active',
  created_at timestamptz default now()
);

create table if not exists exam_submissions (
  id bigint generated by default as identity primary key,
  exam_id text,
  student_id text,
  student_name text,
  answers jsonb,
  correct_answers integer,
  total_questions integer,
  score numeric,
  submitted_at timestamptz default now()
);

-- Realtime
alter publication supabase_realtime add table attendance;


